### ISSUE TITLE
Shorthand character classes

### ISSUE THREAD

**Issue by SicroAtGit** [SicroAtGit/PB-RegEx-Engine#1]
In addition to character classes, there will also be shorthand character classes. However, I'm not quite sure yet which ones there should be and which characters they should cover.

According to this website, the different RegEx engines cover different characters in the shorthand character classes:
https://www.regular-expressions.info/shorthand.html

The current listing:

- `\d` for `[0-9]`
- `\D` for `[^\d]`
- `\t` for the tab character
- `\r` for carriage return (CR)
- `\n` for linefeed (LF)
- `\f` for form feed
- `\s` for `[ \t\r\n\f]`
- `\S` for `[^\s]`
- `\w` for `[A-Za-z0-9_]`
- `\W` for `[^\w]`
- `\h` for `[ \t]`
- `\v` for `[\r\n\f]`

**Comment by tajmone** [comment]
> According to this website, the different RegEx engines cover different characters in the shorthand character classes:
https://www.regular-expressions.info/shorthand.html

BTW, I've bought both [RegexBuddy] and [RegexMagic] form JGS (author of the website you linked), so if you need me to test some RegExs for you I'll happily do it. Both tools have a custom engine that includes [_all_ versions of the major RegEx engines] (so that you can test backward compatibility issues with any engine) plus the [custom engine by JGS], which is very powerful (also documented at the website).

One of these two programs also allows debugging a RegEx to break it down into each single passage, in case you need to compare expected behaviour in your code with actual behaviour by other engines.

As for the shorthand classes to implement, it really depends on what your engine goals are — which I'm guessing is mostly oriented toward lexers creation?

I'm not quite sure that `\h` and `\v` would be all that useful (vertical tabs are not used much in Western languages, and `\t` should suffice in place of `\h`), also these tend to have different meanings across engines.

Some other useful shorthands can be found here:

- [Special Characters] — `\Q`...`\E` for escaping literal sequences.
- [Non-Printable Characters] — `\x` ASCII chars, `\u` Unicode.
- [Anchors] — `\A` and `\Z` are very useful for lexing.
- [Word Boundaries] — Tcl style `\m` and `\M`.

I know that the above don't all qualify as characters shorthand, for some of them are more abstract in nature, but still...




[RegexBuddy]: https://www.regexbuddy.com
[RegexMagic]: https://www.regexmagic.com/
[_all_ versions of the major RegEx engines]: https://www.regexmagic.com/flavors.html
[custom engine by JGS]: https://www.regular-expressions.info/jgsoft.html

[Special Characters]: https://www.regular-expressions.info/characters.html
[Non-Printable Characters]: https://www.regular-expressions.info/nonprint.html
[Anchors]: https://www.regular-expressions.info/anchors.html
[Word Boundaries]: https://www.regular-expressions.info/wordboundaries.html
